# Port of the gateway
server:
  port: 8080

# Gateway configuration
spring:
  cloud:
    gateway:
      routes:
        - id: boats_route
          uri: http://localhost:8090
          predicates:
          - Path=/api/boats/**
          filters:
          - RewritePath=/api/boats(?<segment>), /boats$\{segment}

        - id: flights_route
          uri: http://localhost:8091
          predicates:
          - Path=/api/flights/**
          filters:
          - RewritePath=/api/flights(?<segment>/?), /flights$\{segment}

        - id: hotels_route
          uri: http://localhost:8092
          predicates:
          - Path=/api/hotels/**
          filters:
          - RewritePath=/api/hotels(?<segment>/?), /hotels$\{segment}

        # Swagger routes (needed due to the redirect applied by springdoc)
        - id: boats_route
          uri: http://localhost:8090
          predicates:
          - Path=/boats/docs/**
        
        - id: flights_swagger
          uri: http://localhost:8091
          predicates:
          - Path=/flights/docs/**
        
        - id: hotels_swagger
          uri: http://localhost:8092
          predicates:
          - Path=/hotels/docs/**

management:
  port: 8080
  endpoints:
    web:
      exposure:
        include: health,refresh
eureka:
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      #defaultZone: ${EUREKA_SERVER}
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30

#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
