# Port of the gateway
server:
  port: 8080

# Gateway configuration
spring:
  cloud:
    gateway:
      routes:
        - id: boats_route
          uri: http://localhost:8090
          predicates:
          - Path=/api/boats/**
          filters:
          - RewritePath=/api/boats(?<segment>), /boats$\{segment}

        - id: flights_route
          uri: http://localhost:8091
          predicates:
          - Path=/api/flights/**
          filters:
          - RewritePath=/api/flights(?<segment>/?), /flights$\{segment}

        - id: hotels_route
          uri: http://localhost:8092
          predicates:
          - Path=/api/hotels/**
          filters:
          - RewritePath=/api/hotels(?<segment>/?), /hotels$\{segment}

        # Swagger routes (needed due to the redirect applied by springdoc)
        - id: boats_route
          uri: http://localhost:8090
          predicates:
          - Path=/boats/docs/swagger-ui/**
        
        - id: flights_swagger
          uri: http://localhost:8091
          predicates:
          - Path=/flights/docs/swagger-ui/**
        
        - id: hotels_swagger
          uri: http://localhost:8092
          predicates:
          - Path=/hotels/docs/swagger-ui/**

management:
  port: 8080
  endpoints:
    web:
      exposure:
        include: health,refresh
#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
